### ISSUE TITLE
Use the same file for enter and leave? (AUTOENV_FILE_LEAVE)

### ISSUE THREAD

**Issue by blueyed** [Tarrasch/zsh-autoenv#21]
Currently $AUTOENV_FILE_LEAVE defaults to `.env.leave`, which `.env` is being used for "enter".

I am using `AUTOENV_FILE_LEAVE=.env` myself from the beginning.

I find it more convenient to have it in a single file and use `$autoenv_event` to check which event is being used.

What's your opinion on this?

([I've mentioned this previously](https://github.com/Tarrasch/zsh-autoenv/issues/3#issuecomment-63171998) already, and IIRC `.env.leave` was used to not break backwards compatibility).

**Comment by Tarrasch** [comment]
I think in most cases you only care about the entry block and don't care about the cleanup (if you want cleanup, you just open a new shell).

So, if you would also run the `.env` when you leave the directory, that would start doing strange things you don't guard against it in the `.env` file, which I don't think you should need to.

**Comment by blueyed** [comment]
> if you want cleanup, you just open a new shell

Interesting approach.. :)

Thanks for your feedback, I think it's good to keep it as it is.

**Comment by Tarrasch** [comment]
Cool, thanks for listening. :)
