### ISSUE TITLE
Change default env file names (conflict with typical use of .env)

### ISSUE THREAD

**Issue by blueyed** [Tarrasch/zsh-autoenv#31]
`.env` appears to be commonly used for defining key-value pairs of environment variables (e.g. with foreman etc).

We should change our defaults.

What about using `.autoenv.zsh` instead of `.env`, and `.autoenv_leave.zsh` instead of `.env_leave`?

**Comment by Tarrasch** [comment]
I'm all for it :)

Just for future reference, can you link to this foreman project's `.env` file?

**Comment by blueyed** [comment]
It's mentioned in the man page: https://ddollar.github.io/foreman/

    ENVIRONMENT

    If a .env file exists in the current directory, the default environment
    will be read from it. This file should contain key/value pairs, separated
    by =, with one key/value pair per line.

    FOO=bar
    BAZ=qux

Also relevant: https://github.com/tpope/vim-dotenv

**Comment by Tarrasch** [comment]
Thanks! Very useful resources!

**Comment by blueyed** [comment]
See #32.

**Comment by ryneeverett** [comment]
I understand the decision to change the name to avoid collisions with foreman, but why make the it zsh-specific? Wouldn't any implementation of autoenv work the same? Why not just `.autoenv`/`.autoenv_leave`?

**Comment by blueyed** [comment]
@ryneeverett 
It makes it clear that it is a Zsh file, where the syntax might differ from other shells.

I am open to change the default again, but not convinced yet.

**Comment by Tarrasch** [comment]
Agree with @blueyed for the reasons he said. :)

**Comment by ryneeverett** [comment]
@blueyed Fair enough, though I would personally value compatibility with bash autoenv more than the ability to write zshscript (they could both execute `/bin/sh .autoenv`)

Also, as someone who types `touch .env` multiple times a day, the length of the file name is disappointing. Guess I'll have to add one more alias I'll never remember, haha.

**Comment by blueyed** [comment]
@ryneeverett 
You know that this is a setting that can be configured?!
Just set/change `AUTOENV_FILE_ENTER` and `AUTOENV_FILE_LEAVE`.
This would typically be done before sourcing the plugin, but could be done later, too.

**Comment by ryneeverett** [comment]
@blueyed thanks, hadn't noticed that!
