### ISSUE TITLE
Error when entering any directory

### ISSUE THREAD

**Issue by devinsba** [Tarrasch/zsh-autoenv#38]
This is happening with the latest master branch installed as an anitgen bundle

```
_autoenv_debug:local:1: not valid in this context: handler:
```

**Comment by blueyed** [comment]
Does changing the line to `local msg="$1"` help (in `_autoenv_debug`)?
How did you install it exactly?

**Comment by devinsba** [comment]
Yes, that fixes it.

I have in my zshrc which clones the master branch:

```
antigen bundle Tarrasch/zsh-autoenv
```

I have this problem on both my debian box at home and my OSX box here at work.

I'm on `zsh 5.0.5 (x86_64-apple-darwin14.0)` here at work if that helps

**Comment by blueyed** [comment]
Can you provide the output of `setopt`, to see if there is some option triggering this?

**Comment by devinsba** [comment]
I'm not completely sure what I am looking at here. This is the options from a shell with the plugin loaded. The list is the same when I disable the plugin

```
% setopt
alwaystoend
autocd
autopushd
cdablevars
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
shwordsplit
zle
```

**Comment by blueyed** [comment]
It's triggered by `shwordsplit`, which appears to trigger a bug in Zsh 5.0.5 (could not reproduce it with 5.1.1).

Thanks for the report!

**Comment by devinsba** [comment]
Awesome, thanks
