### ISSUE TITLE
variables not properly exported ? 

### ISSUE THREAD

**Issue by sulphur** [Tarrasch/zsh-autoenv#40]
hi, 

in my .autoenv.zsh i set 
```
KAFKA_BROKERS="192.168.99.100:9092"
```
when i enter the directory i can do 
`echo $KAFKA_BROKERS` which works as expected
however when i run `export -a` the variables is not listed there hence it does not work in my Elixir project

I use 
```
zsh --version
zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```
with latest zgen

**Comment by blueyed** [comment]
The vars are not exported automatically.  Use `export` or `autostash`, which will also export it.

Closing the issue, but feel free to reopen in case I'm missing anything.

**Comment by blueyed** [comment]
Maybe this could be improved in the documentation?
What do you think?  (PR is welcome of course).
