### ISSUE TITLE
Please add the ability to stash aliases

### ISSUE THREAD

**Issue by cazador481** [Tarrasch/zsh-autoenv#43]

**Comment by blueyed** [comment]
Thanks for the report.
I think ti should work - what have you tried?

**Comment by cazador481** [comment]
I tried stash dzil and stash alias dzil.
Both tried to stash the env variable dzil, and the second one also tried to
stash the env variable alias

**Comment by blueyed** [comment]
I've added a test for this (https://github.com/Tarrasch/zsh-autoenv/pull/44) - it seems to be working.

If you could provide a failing test for your use case that would help a lot.

**Comment by blueyed** [comment]
Ah, but the test has no env variable with the same name.

It seems that the env variable is then preferred over the alias?!
Should both be handled in your opinion?

**Comment by blueyed** [comment]
Meh, also not run the actual test locally, which seems to fail really.

**Comment by blueyed** [comment]
Using `autostash alias some_alias="echo NEW_ALIAS"'` seems to work however.

**Comment by cazador481** [comment]
Actually in my case I didn't have an ENV variable matching the alias, but when I tried to stash again it told me that I had already stashed the env.

**Comment by blueyed** [comment]
Assuming this is fixed/resolved - at least it is tested by now.
Please let me know / reopen if I've missed something.

**Comment by pjgoodall** [comment]
does not seem to be working. If I have consecutive `autostash alias` it complains i have already stashed `alias`
