### ISSUE TITLE
error message, not working

### ISSUE THREAD

**Issue by rubycut** [Tarrasch/zsh-autoenv#48]
after install:

```
Would you like to authorize it? (type 'yes') yes
_autoenv_authorize:3: no such file or directory: /root/.local/share/autoenv_auth
```

**Comment by rubycut** [comment]
```
mkdir -p /root/.local/share
```
Solves the issue.

**Comment by blueyed** [comment]
Thanks for the report!

Should be fixed in https://github.com/Tarrasch/zsh-autoenv/issues/48, which I'll merge when it's green.

**Comment by rubycut** [comment]
@blueyed Amazing stuff, tests for zsh commands called cram, I didn't even know this existed. :)

**Comment by blueyed** [comment]
Yes, it's for shell scripts in general, and makes me very confident to make changes on this project.. :)
