### ISSUE TITLE
Way to invoke _autoenv_chpwd_handler from script ?

### ISSUE THREAD

**Issue by mickaelperrin** [Tarrasch/zsh-autoenv#50]
Hi,

I use a script that generate .autoenv.zsh files.

Is it possible to call _autoenv_chpwd_handler from this script and get it working in the current terminal session when it ends ?

I would like to prevent the need to call _autoenv_chpwd_handler manually or to leave/enter the current directory when the script ends.

Don't see how it could be possible, but you can have some hints.

Regards,

**Comment by blueyed** [comment]
You can use `cd .` to trigger the chpwd handler.

**Comment by blueyed** [comment]
Closing this for now, please reopen it in case that's not good enough.

**Comment by mickaelperrin** [comment]
Ok thank you, so no way to get it working in a script, without having to type `cd .` manually at the end ?

**Comment by Tarrasch** [comment]
Needless to say, you will improve code clarity by adding a `# comment`, perhaps even linking directly to this issue.

**Comment by blueyed** [comment]
The `cd .` can be in the script, of course.
