### ISSUE TITLE
autostash not working when changing out of child directory

### ISSUE THREAD

**Issue by peterjuras** [Tarrasch/zsh-autoenv#77]
autostash appears to not restore/unset environment variables when changing out of a child directory instead of the directory where autostash is part of the .autoenv.zsh file.

Steps to reproduce:

1. export AUTOENV_LOOK_UPWARDS=1
1. Create a directory ~/env1
2. Create ~/env1/.autoenv.zsh with "autostash TEST=YES"
3. Create a directory ~/env1/env2
4. Open a new shell starting at ~
5. cd into ~/env1/env2 -> echo $TEST is now YES
6. cd into ~ directly

Current behavior

-> echo $TEST is still YES

Expected behavior

-> echo $TEST is empty

**Comment by blueyed** [comment]
I'm surprised this would not work, but have to investigate.

**Comment by blueyed** [comment]
Thanks for the report, fixed.

**Comment by peterjuras** [comment]
Thanks a lot!
